"use client";

import React, { useState, useEffect, useRef, useMemo } from "react";
import { 
  CloudUpload, 
  Search, 
  ChevronDown, 
  LayoutGrid, 
  List, 
  Star, 
  MoreVertical, 
  Upload, 
  Sparkles, 
  Scan, 
  FolderPlus, 
  Lightbulb, 
  Check, 
  Scale, 
  FileText, 
  Image as ImageIcon, 
  ChevronLeft, 
  ChevronRight,
  X,
  Eye,
  Download,
  Trash2,
  HardDrive,
  Cloud,
  FileCheck,
  AlertCircle,
  Loader2,
  ExternalLink
} from "lucide-react";
import { useRouter } from "@/i18n/routing";
import { auth, db } from "@/lib/firebase";
import { 
  collection, 
  onSnapshot, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  doc, 
  serverTimestamp 
} from "firebase/firestore";
import { onAuthStateChanged, User } from "firebase/auth";

export interface LegalDocument {
  id: string;
  name: string;
  type: "Evidence" | "Agreement / Contract" | "AI Generated" | "Legal Notice" | "Financial Record" | "ID Proof" | "Other";
  relatedCase: string;
  caseId?: string;
  uploadedBy: string;
  uploadedOn: string;
  size: string;
  sizeBytes: number;
  isFavorite: boolean;
  storageTarget: "firebase" | "localstorage" | "both";
  dataUrl?: string;
  notes?: string;
  isTrash?: boolean;
}

const INITIAL_DEMO_DOCUMENTS: LegalDocument[] = [
  {
    id: "demo-doc-1",
    name: "Payment Receipt - Screenshot",
    type: "Evidence",
    relatedCase: "Online Transaction Fraud",
    caseId: "NYA-2025-0512-001",
    uploadedBy: "Uploaded by You",
    uploadedOn: "12 May 2025, 11:30 AM",
    size: "1.2 MB",
    sizeBytes: 1258291,
    isFavorite: false,
    storageTarget: "both",
  },
  {
    id: "demo-doc-2",
    name: "Chat with Seller",
    type: "Evidence",
    relatedCase: "Online Transaction Fraud",
    caseId: "NYA-2025-0512-001",
    uploadedBy: "Uploaded by You",
    uploadedOn: "12 May 2025, 11:28 AM",
    size: "845 KB",
    sizeBytes: 865280,
    isFavorite: false,
    storageTarget: "both",
  },
  {
    id: "demo-doc-3",
    name: "Order Invoice",
    type: "Evidence",
    relatedCase: "Online Transaction Fraud",
    caseId: "NYA-2025-0512-001",
    uploadedBy: "Uploaded by You",
    uploadedOn: "12 May 2025, 11:25 AM",
    size: "1.8 MB",
    sizeBytes: 1887436,
    isFavorite: false,
    storageTarget: "both",
  },
  {
    id: "demo-doc-4",
    name: "Complaint Draft",
    type: "AI Generated",
    relatedCase: "Online Transaction Fraud",
    caseId: "NYA-2025-0512-001",
    uploadedBy: "Generated by NyayaAI",
    uploadedOn: "12 May 2025, 01:15 PM",
    size: "64 KB",
    sizeBytes: 65536,
    isFavorite: true,
    storageTarget: "both",
  },
  {
    id: "demo-doc-5",
    name: "ID Proof - Aadhaar Card",
    type: "ID Proof",
    relatedCase: "Online Transaction Fraud",
    caseId: "NYA-2025-0512-001",
    uploadedBy: "Uploaded by You",
    uploadedOn: "12 May 2025, 11:10 AM",
    size: "1.1 MB",
    sizeBytes: 1153433,
    isFavorite: false,
    storageTarget: "both",
  },
  {
    id: "demo-doc-6",
    name: "Refund Request Letter",
    type: "AI Generated",
    relatedCase: "Online Transaction Fraud",
    caseId: "NYA-2025-0512-001",
    uploadedBy: "Generated by NyayaAI",
    uploadedOn: "12 May 2025, 01:20 PM",
    size: "78 KB",
    sizeBytes: 79872,
    isFavorite: false,
    storageTarget: "both",
  }
];

const LOCAL_STORAGE_KEY = "nyaya_stored_documents";

export default function DocumentsPage() {
  const router = useRouter();
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [documents, setDocuments] = useState<LegalDocument[]>(INITIAL_DEMO_DOCUMENTS);
  
  // UI Controls
  const [activeTab, setActiveTab] = useState<string>("All Documents");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [typeFilter, setTypeFilter] = useState<string>("All Types");
  const [sortBy, setSortBy] = useState<"newest" | "oldest" | "size" | "name">("newest");
  const [viewMode, setViewMode] = useState<"list" | "grid">("list");
  
  // Modals
  const [isUploadModalOpen, setIsUploadModalOpen] = useState(false);
  const [previewDoc, setPreviewDoc] = useState<LegalDocument | null>(null);
  
  // Upload Form State
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [fileBase64, setFileBase64] = useState<string>("");
  const [uploadDocName, setUploadDocName] = useState<string>("");
  const [uploadDocType, setUploadDocType] = useState<LegalDocument["type"]>("Evidence");
  const [uploadRelatedCase, setUploadRelatedCase] = useState<string>("General Legal Document");
  const [storageDestination, setStorageDestination] = useState<"both" | "firebase" | "localstorage">("both");
  const [isUploading, setIsUploading] = useState(false);
  const [statusNotice, setStatusNotice] = useState<{ message: string; type: "success" | "error" } | null>(null);

  // Listen to Auth State & Sync Documents
  useEffect(() => {
    const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);

      // 1. First load from localStorage for instant display
      const localData = localStorage.getItem(LOCAL_STORAGE_KEY);
      let localDocs: LegalDocument[] = [];
      if (localData) {
        try {
          localDocs = JSON.parse(localData);
        } catch {
          localDocs = [];
        }
      }

      if (user) {
        // 2. Load and sync from Firestore subcollection: users/{userId}/documents
        const docsRef = collection(db, "users", user.uid, "documents");
        const unsubscribeFirestore = onSnapshot(docsRef, (snapshot) => {
          const remoteDocs: LegalDocument[] = snapshot.docs.map((docSnap) => {
            const data = docSnap.data();
            return {
              id: docSnap.id,
              name: data.name || "Untitled Document",
              type: data.type || "Evidence",
              relatedCase: data.relatedCase || "General Legal Document",
              caseId: data.caseId,
              uploadedBy: data.uploadedBy || "Uploaded by You",
              uploadedOn: data.uploadedOn || new Date().toLocaleString(),
              size: data.size || "Unknown",
              sizeBytes: data.sizeBytes || 0,
              isFavorite: Boolean(data.isFavorite),
              storageTarget: data.storageTarget || "firebase",
              dataUrl: data.dataUrl || "",
              notes: data.notes || "",
              isTrash: Boolean(data.isTrash),
            };
          });

          // Merge: Remote Firestore docs + User's local uploads + Initial demos
          const combinedMap = new Map<string, LegalDocument>();
          INITIAL_DEMO_DOCUMENTS.forEach(d => combinedMap.set(d.id, d));
          localDocs.forEach(d => combinedMap.set(d.id, d));
          remoteDocs.forEach(d => combinedMap.set(d.id, d));

          const merged = Array.from(combinedMap.values());
          setDocuments(merged);
          localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(merged));
        }, () => {
          // If Firestore read fails or is offline, fall back to local
          const fallback = [...INITIAL_DEMO_DOCUMENTS, ...localDocs];
          setDocuments(fallback);
        });

        return () => unsubscribeFirestore();
      } else {
        // Offline / Unauthenticated Mode: Merge demo docs + local uploads
        const combined = [...INITIAL_DEMO_DOCUMENTS, ...localDocs.filter(d => !INITIAL_DEMO_DOCUMENTS.some(x => x.id === d.id))];
        setDocuments(combined);
      }
    });

    return () => unsubscribeAuth();
  }, []);

  // Format File Size
  const formatBytes = (bytes: number): string => {
    if (bytes === 0) return "0 KB";
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + " KB";
    return (bytes / (1024 * 1024)).toFixed(1) + " MB";
  };

  // Handle File Selection
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setSelectedFile(file);
    if (!uploadDocName) {
      const cleanName = file.name.replace(/\.[^/.]+$/, "");
      setUploadDocName(cleanName);
    }

    const reader = new FileReader();
    reader.onload = () => {
      setFileBase64(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  // Handle Drag & Drop
  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    const file = e.dataTransfer.files?.[0];
    if (file) {
      setSelectedFile(file);
      if (!uploadDocName) {
        setUploadDocName(file.name.replace(/\.[^/.]+$/, ""));
      }
      const reader = new FileReader();
      reader.onload = () => {
        setFileBase64(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  // Upload and Save Document to Firebase and/or LocalStorage
  const handleUploadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!uploadDocName.trim()) {
      setStatusNotice({ message: "Please provide a document title", type: "error" });
      return;
    }

    setIsUploading(true);
    setStatusNotice(null);

    try {
      const now = new Date();
      const formattedDate = now.toLocaleDateString("en-IN", {
        day: "numeric",
        month: "short",
        year: "numeric"
      }) + ", " + now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

      const sizeFormatted = selectedFile ? formatBytes(selectedFile.size) : "50 KB";
      const sizeBytes = selectedFile ? selectedFile.size : 51200;

      const newDoc: LegalDocument = {
        id: "doc_" + Date.now(),
        name: uploadDocName.trim(),
        type: uploadDocType,
        relatedCase: uploadRelatedCase.trim() || "General Legal Document",
        caseId: "NYA-" + now.getFullYear() + "-CUSTOM",
        uploadedBy: "Uploaded by You",
        uploadedOn: formattedDate,
        size: sizeFormatted,
        sizeBytes: sizeBytes,
        isFavorite: false,
        storageTarget: storageDestination,
        dataUrl: fileBase64 || "",
        isTrash: false,
      };

      // 1. Save to Firebase Firestore if requested or authenticated
      let firestoreSaved = false;
      if ((storageDestination === "both" || storageDestination === "firebase") && currentUser) {
        try {
          const docRef = await addDoc(collection(db, "users", currentUser.uid, "documents"), {
            name: newDoc.name,
            type: newDoc.type,
            relatedCase: newDoc.relatedCase,
            caseId: newDoc.caseId,
            uploadedBy: newDoc.uploadedBy,
            uploadedOn: newDoc.uploadedOn,
            size: newDoc.size,
            sizeBytes: newDoc.sizeBytes,
            isFavorite: false,
            storageTarget: "firebase",
            // Keep dataUrl lightweight in Firestore (if < 700KB)
            dataUrl: sizeBytes < 700000 ? fileBase64 : "",
            createdAt: serverTimestamp(),
            isTrash: false,
          });
          newDoc.id = docRef.id;
          firestoreSaved = true;
        } catch (fbErr) {
          console.warn("Firestore save notice:", fbErr);
        }
      }

      // 2. Always persist to localStorage for offline access and local backup
      const updatedList = [newDoc, ...documents];
      setDocuments(updatedList);
      localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(updatedList));

      // Reset form
      setSelectedFile(null);
      setFileBase64("");
      setUploadDocName("");
      setIsUploadModalOpen(false);

      const storageMsg = firestoreSaved 
        ? "Document saved to Firebase Cloud & LocalStorage!" 
        : "Document saved securely to LocalStorage!";
      setStatusNotice({ message: storageMsg, type: "success" });

      setTimeout(() => setStatusNotice(null), 5000);
    } catch (err: any) {
      setStatusNotice({ message: err?.message || "Failed to upload document", type: "error" });
    } finally {
      setIsUploading(false);
    }
  };

  // Toggle Favorite Status
  const handleToggleFavorite = async (docId: string, currentStatus: boolean) => {
    const updated = documents.map(d => d.id === docId ? { ...d, isFavorite: !currentStatus } : d);
    setDocuments(updated);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(updated));

    if (currentUser && !docId.startsWith("demo-doc-")) {
      try {
        await updateDoc(doc(db, "users", currentUser.uid, "documents", docId), {
          isFavorite: !currentStatus
        });
      } catch (e) {
        console.warn("Favorite update sync notice:", e);
      }
    }
  };

  // Delete Document
  const handleDeleteDocument = async (docId: string) => {
    const updated = documents.filter(d => d.id !== docId);
    setDocuments(updated);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(updated));

    if (previewDoc?.id === docId) {
      setPreviewDoc(null);
    }

    if (currentUser && !docId.startsWith("demo-doc-")) {
      try {
        await deleteDoc(doc(db, "users", currentUser.uid, "documents", docId));
      } catch (e) {
        console.warn("Firestore delete notice:", e);
      }
    }
    setStatusNotice({ message: "Document removed successfully", type: "success" });
    setTimeout(() => setStatusNotice(null), 3000);
  };

  // Download Document
  const handleDownload = (d: LegalDocument) => {
    if (d.dataUrl) {
      const a = document.createElement("a");
      a.href = d.dataUrl;
      a.download = `${d.name.replace(/\s+/g, "_")}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } else {
      // Create a plain text fallback export
      const textContent = `NYAYAAI LEGAL DOCUMENT EXPORT\n============================\nDocument Name: ${d.name}\nType: ${d.type}\nRelated Case: ${d.relatedCase} (${d.caseId || ""})\nUploaded On: ${d.uploadedOn}\nStorage Target: ${d.storageTarget}\n\nStatus: Verified Indian Legal Record.\nGenerated by NyayaAI Legal Assistance System.`;
      const blob = new Blob([textContent], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${d.name.replace(/\s+/g, "_")}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  // Navigate to AI Analysis
  const handleAnalyzeWithAI = (d: LegalDocument) => {
    router.push(`/dashboard/document-analysis?docTitle=${encodeURIComponent(d.name)}&docType=${encodeURIComponent(d.type)}`);
  };

  // Filtered & Sorted Documents
  const filteredDocuments = useMemo(() => {
    return documents.filter((d) => {
      // Tab filter
      if (activeTab === "My Uploads" && d.uploadedBy.includes("AI")) return false;
      if (activeTab === "AI Generated" && !d.uploadedBy.includes("AI")) return false;
      if (activeTab === "Case Documents" && (!d.relatedCase || d.relatedCase.includes("General"))) return false;
      if (activeTab === "Favorites" && !d.isFavorite) return false;
      if (activeTab === "Trash" && !d.isTrash) return false;
      if (activeTab !== "Trash" && d.isTrash) return false;

      // Type dropdown filter
      if (typeFilter !== "All Types" && d.type !== typeFilter) return false;

      // Search query
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        return (
          d.name.toLowerCase().includes(q) ||
          d.relatedCase.toLowerCase().includes(q) ||
          d.type.toLowerCase().includes(q)
        );
      }
      return true;
    }).sort((a, b) => {
      if (sortBy === "name") return a.name.localeCompare(b.name);
      if (sortBy === "size") return b.sizeBytes - a.sizeBytes;
      if (sortBy === "oldest") return a.id.localeCompare(b.id);
      return b.id.localeCompare(a.id); // newest first
    });
  }, [documents, activeTab, typeFilter, searchQuery, sortBy]);

  // Compute Total Storage Used
  const totalSizeBytes = useMemo(() => {
    return documents.reduce((acc, curr) => acc + (curr.sizeBytes || 0), 0);
  }, [documents]);

  const totalUsedMb = (totalSizeBytes / (1024 * 1024)).toFixed(1);
  const totalLimitMb = 10240; // 10 GB
  const usedPercentage = Math.min(100, Math.max(1, Math.round((totalSizeBytes / (totalLimitMb * 1024 * 1024)) * 100)));

  return (
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-10 py-8 space-y-6">
      
      {/* Toast Notice */}
      {statusNotice && (
        <div className={`p-4 rounded-xl flex items-center justify-between text-xs font-bold transition-all shadow-md ${
          statusNotice.type === "success" 
            ? "bg-emerald-50 border border-emerald-300 text-emerald-900" 
            : "bg-red-50 border border-red-300 text-red-900"
        }`}>
          <div className="flex items-center gap-2">
            {statusNotice.type === "success" ? <Check size={16} className="text-emerald-600" /> : <AlertCircle size={16} className="text-red-600" />}
            <span>{statusNotice.message}</span>
          </div>
          <button onClick={() => setStatusNotice(null)} className="hover:opacity-70">
            <X size={14} />
          </button>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-2">
        <div>
          <h1 className="text-3xl font-black text-text-main tracking-tight mb-1">Legal Documents</h1>
          <p className="text-sm text-text-muted font-medium">
            Upload, organize, and inspect all case evidence and contracts backed by Firebase Cloud & LocalStorage.
          </p>
        </div>
        <button 
          onClick={() => {
            setSelectedFile(null);
            setUploadDocName("");
            setFileBase64("");
            setIsUploadModalOpen(true);
          }}
          className="flex items-center gap-2 px-5 py-2.5 bg-black text-white rounded-xl text-sm font-bold hover:bg-neutral-800 transition-all shadow-sm shrink-0 active:scale-95"
        >
          <CloudUpload size={18} />
          Upload Document
        </button>
      </div>

      <div className="space-y-8">
        
        {/* Main Content (Table & Grid Area) */}
        <div className="space-y-6">
          
          {/* Filters (Tabs) */}
          <div className="flex items-center gap-2 overflow-x-auto scrollbar-hide pb-2">
            {["All Documents", "My Uploads", "Case Documents", "AI Generated", "Favorites", "Trash"].map((tab) => (
              <button 
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-2 rounded-full text-xs font-bold transition-all shrink-0 ${
                  activeTab === tab 
                    ? "bg-black text-white shadow-xs" 
                    : "bg-bg-subtle text-text-muted hover:text-text-main hover:bg-gray-200"
                }`}
              >
                {tab} {tab === "All Documents" && `(${documents.length})`}
              </button>
            ))}
          </div>

          {/* Main Table Card */}
          <div className="bg-white border border-border-main rounded-2xl shadow-sm overflow-hidden">
            
            {/* Toolbar */}
            <div className="p-4 border-b border-border-main flex flex-col md:flex-row gap-4 items-center justify-between">
              
              <div className="relative w-full md:max-w-md">
                <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-text-light" />
                <input 
                  type="text" 
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search by document name, case, or type..."
                  className="w-full pl-9 pr-4 py-2 bg-bg-subtle border border-border-main rounded-xl text-xs font-semibold outline-none focus:border-black focus:ring-1 focus:ring-black transition-all"
                />
                {searchQuery && (
                  <button onClick={() => setSearchQuery("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-text-muted hover:text-black">
                    <X size={14} />
                  </button>
                )}
              </div>

              <div className="flex items-center gap-3 w-full md:w-auto">
                {/* Type Filter */}
                <select
                  value={typeFilter}
                  onChange={(e) => setTypeFilter(e.target.value)}
                  className="px-3 py-2 border border-border-main rounded-xl text-xs font-bold bg-white text-text-main outline-none cursor-pointer hover:bg-bg-subtle"
                >
                  <option value="All Types">All Types</option>
                  <option value="Evidence">Evidence</option>
                  <option value="Agreement / Contract">Agreement / Contract</option>
                  <option value="AI Generated">AI Generated</option>
                  <option value="Legal Notice">Legal Notice</option>
                  <option value="ID Proof">ID Proof</option>
                  <option value="Other">Other</option>
                </select>

                {/* Sort Order */}
                <select
                  value={sortBy}
                  onChange={(e: any) => setSortBy(e.target.value)}
                  className="px-3 py-2 border border-border-main rounded-xl text-xs font-bold bg-white text-text-main outline-none cursor-pointer hover:bg-bg-subtle"
                >
                  <option value="newest">Sort: Newest First</option>
                  <option value="oldest">Sort: Oldest First</option>
                  <option value="size">Sort: Size (Largest)</option>
                  <option value="name">Sort: Name (A-Z)</option>
                </select>
                
                {/* View Mode Toggle */}
                <div className="flex items-center border border-border-main rounded-xl overflow-hidden shrink-0 ml-auto md:ml-0">
                  <button 
                    onClick={() => setViewMode("list")}
                    aria-label="List view"
                    className={`p-2 transition-colors ${viewMode === "list" ? "bg-black text-white" : "bg-white text-text-muted hover:bg-bg-subtle"}`}
                  >
                    <List size={16} />
                  </button>
                  <button 
                    onClick={() => setViewMode("grid")}
                    aria-label="Grid view"
                    className={`p-2 transition-colors ${viewMode === "grid" ? "bg-black text-white" : "bg-white text-text-muted hover:bg-bg-subtle"}`}
                  >
                    <LayoutGrid size={16} />
                  </button>
                </div>
              </div>

            </div>

            {/* List / Table View */}
            {viewMode === "list" ? (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-sm">
                  <thead className="bg-bg-subtle border-b border-border-main text-text-muted font-bold text-[11px] uppercase tracking-wider whitespace-nowrap">
                    <tr>
                      <th className="px-6 py-4">Document Name</th>
                      <th className="px-6 py-4">Type</th>
                      <th className="px-6 py-4">Related Case</th>
                      <th className="px-6 py-4">Storage Source</th>
                      <th className="px-6 py-4">Uploaded On</th>
                      <th className="px-6 py-4">Size</th>
                      <th className="px-6 py-4 text-center">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border-main">
                    {filteredDocuments.length === 0 ? (
                      <tr>
                        <td colSpan={7} className="px-6 py-12 text-center text-text-muted">
                          <FileText size={36} className="mx-auto mb-2 text-text-light opacity-50" />
                          <p className="font-bold text-sm text-text-main">No documents found</p>
                          <p className="text-xs text-text-muted mt-1">Try adjusting your filters or upload a new legal document.</p>
                          <button
                            onClick={() => setIsUploadModalOpen(true)}
                            className="mt-4 px-4 py-2 bg-black text-white text-xs font-bold rounded-xl hover:bg-neutral-800 transition-all inline-flex items-center gap-1.5"
                          >
                            <CloudUpload size={14} /> Upload Document
                          </button>
                        </td>
                      </tr>
                    ) : (
                      filteredDocuments.map((docItem) => (
                        <tr key={docItem.id} className="hover:bg-bg-subtle/40 transition-colors group">
                          {/* Name */}
                          <td className="px-6 py-4">
                            <div className="flex items-start gap-3">
                              <div className={`w-10 h-10 rounded-xl flex items-center justify-center border shrink-0 ${
                                docItem.type === "Evidence" 
                                  ? "bg-red-50 text-red-600 border-red-100"
                                  : docItem.type === "AI Generated"
                                  ? "bg-purple-50 text-purple-600 border-purple-100"
                                  : docItem.type === "ID Proof"
                                  ? "bg-amber-50 text-amber-600 border-amber-100"
                                  : "bg-blue-50 text-blue-600 border-blue-100"
                              }`}>
                                {docItem.type === "Evidence" ? <ImageIcon size={19} /> : <FileText size={19} />}
                              </div>
                              <div className="min-w-0">
                                <p 
                                  onClick={() => setPreviewDoc(docItem)}
                                  className="font-bold text-text-main hover:underline cursor-pointer truncate max-w-[220px]"
                                  title={docItem.name}
                                >
                                  {docItem.name}
                                </p>
                                <p className="text-[11px] text-text-muted mt-0.5">{docItem.uploadedBy}</p>
                              </div>
                            </div>
                          </td>

                          {/* Type */}
                          <td className="px-6 py-4">
                            <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold border ${
                              docItem.type === "AI Generated"
                                ? "bg-purple-50 border-purple-200 text-purple-700"
                                : docItem.type === "Evidence"
                                ? "bg-rose-50 border-rose-200 text-rose-700"
                                : "bg-gray-100 border-gray-200 text-gray-700"
                            }`}>
                              {docItem.type}
                            </span>
                          </td>

                          {/* Related Case */}
                          <td className="px-6 py-4">
                            <p className="font-bold text-text-main text-xs truncate max-w-[180px]">{docItem.relatedCase}</p>
                            {docItem.caseId && (
                              <p className="text-[10px] text-text-muted font-mono">{docItem.caseId}</p>
                            )}
                          </td>

                          {/* Storage Source */}
                          <td className="px-6 py-4">
                            <span className="inline-flex items-center gap-1 text-[11px] font-bold text-text-main bg-bg-subtle px-2.5 py-1 rounded-lg border border-border-main">
                              {docItem.storageTarget === "firebase" ? (
                                <>
                                  <Cloud size={12} className="text-blue-600" /> Firebase Cloud
                                </>
                              ) : docItem.storageTarget === "localstorage" ? (
                                <>
                                  <HardDrive size={12} className="text-emerald-600" /> Local Storage
                                </>
                              ) : (
                                <>
                                  <Cloud size={12} className="text-blue-600" /> Cloud + Local
                                </>
                              )}
                            </span>
                          </td>

                          {/* Uploaded On */}
                          <td className="px-6 py-4">
                            <p className="font-bold text-text-main text-xs">{docItem.uploadedOn}</p>
                          </td>

                          {/* Size */}
                          <td className="px-6 py-4 text-xs font-bold text-text-muted">
                            {docItem.size}
                          </td>

                          {/* Actions */}
                          <td className="px-6 py-4 text-center">
                            <div className="flex items-center justify-center gap-1.5 text-text-muted">
                              <button 
                                onClick={() => handleToggleFavorite(docItem.id, docItem.isFavorite)}
                                aria-label="Toggle favorite"
                                className={`p-1.5 rounded-lg hover:bg-bg-subtle transition-colors ${
                                  docItem.isFavorite ? "text-amber-500 fill-amber-500" : "hover:text-amber-500"
                                }`}
                                title={docItem.isFavorite ? "Remove favorite" : "Add to favorites"}
                              >
                                <Star size={16} className={docItem.isFavorite ? "fill-amber-500 text-amber-500" : ""} />
                              </button>
                              
                              <button 
                                onClick={() => setPreviewDoc(docItem)}
                                aria-label="Preview document"
                                className="p-1.5 rounded-lg hover:bg-bg-subtle hover:text-black transition-colors"
                                title="Preview document details"
                              >
                                <Eye size={16} />
                              </button>

                              <button 
                                onClick={() => handleAnalyzeWithAI(docItem)}
                                aria-label="Analyze with AI"
                                className="p-1.5 rounded-lg hover:bg-purple-50 hover:text-purple-700 transition-colors"
                                title="Analyze loopholes with NyayaAI"
                              >
                                <Sparkles size={16} />
                              </button>

                              <button 
                                onClick={() => handleDownload(docItem)}
                                aria-label="Download document"
                                className="p-1.5 rounded-lg hover:bg-bg-subtle hover:text-black transition-colors"
                                title="Download"
                              >
                                <Download size={16} />
                              </button>

                              <button 
                                onClick={() => handleDeleteDocument(docItem.id)}
                                aria-label="Delete document"
                                className="p-1.5 rounded-lg hover:bg-red-50 hover:text-red-600 transition-colors"
                                title="Delete document"
                              >
                                <Trash2 size={16} />
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            ) : (
              /* Grid View */
              <div className="p-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {filteredDocuments.map((docItem) => (
                  <div 
                    key={docItem.id} 
                    className="border border-border-main rounded-2xl p-4 bg-white hover:border-black transition-all flex flex-col justify-between shadow-xs group"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <div className="w-10 h-10 rounded-xl bg-bg-subtle border border-border-main flex items-center justify-center">
                          <FileText size={20} className="text-text-main" />
                        </div>
                        <div className="flex items-center gap-1">
                          <button 
                            onClick={() => handleToggleFavorite(docItem.id, docItem.isFavorite)}
                            className="p-1.5 text-text-muted hover:text-amber-500 rounded-md"
                          >
                            <Star size={15} className={docItem.isFavorite ? "fill-amber-500 text-amber-500" : ""} />
                          </button>
                          <button 
                            onClick={() => handleDeleteDocument(docItem.id)}
                            className="p-1.5 text-text-muted hover:text-red-500 rounded-md"
                          >
                            <Trash2 size={15} />
                          </button>
                        </div>
                      </div>

                      <h4 
                        onClick={() => setPreviewDoc(docItem)}
                        className="font-bold text-sm text-text-main hover:underline cursor-pointer truncate"
                      >
                        {docItem.name}
                      </h4>
                      <p className="text-[11px] text-text-muted mt-0.5 truncate">{docItem.relatedCase}</p>
                    </div>

                    <div className="mt-4 pt-3 border-t border-border-main flex items-center justify-between text-xs">
                      <span className="font-bold text-text-muted text-[11px]">{docItem.size}</span>
                      <div className="flex items-center gap-1">
                        <button 
                          onClick={() => handleAnalyzeWithAI(docItem)}
                          className="px-2 py-1 text-[10px] font-bold bg-purple-50 text-purple-700 rounded-md hover:bg-purple-100 flex items-center gap-1"
                        >
                          <Sparkles size={11} /> AI Audit
                        </button>
                        <button 
                          onClick={() => handleDownload(docItem)}
                          className="p-1 text-text-muted hover:text-black rounded-md"
                        >
                          <Download size={14} />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Footer / Pagination & Count */}
            <div className="p-4 border-t border-border-main flex flex-col sm:flex-row items-center justify-between gap-4">
              <p className="text-xs font-bold text-text-muted">
                Showing {filteredDocuments.length} of {documents.length} legal documents
              </p>
              
              <div className="flex items-center gap-1.5">
                <button className="w-8 h-8 flex items-center justify-center border border-border-main rounded-lg text-text-muted hover:bg-bg-subtle transition-colors">
                  <ChevronLeft size={16} />
                </button>
                <button className="w-8 h-8 flex items-center justify-center bg-black text-white rounded-lg text-xs font-bold shadow-xs">
                  1
                </button>
                <button className="w-8 h-8 flex items-center justify-center border border-border-main rounded-lg text-text-main hover:bg-bg-subtle transition-colors">
                  <ChevronRight size={16} />
                </button>
              </div>
            </div>

          </div>

        </div>

        {/* Bottom Section: 3-Column Grid (Storage Usage, Quick Actions, Tips) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-2">
          
          {/* Storage Usage Card */}
          <div className="bg-white border border-border-main rounded-2xl p-6 shadow-sm flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-sm text-text-main">Storage Usage</h3>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">
                  Firebase Cloud Active
                </span>
              </div>
              
              <div className="flex items-center gap-6 mb-6">
                {/* Circular Progress */}
                <div className="relative w-24 h-24 flex items-center justify-center rounded-full shrink-0">
                  <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                    <path
                      className="text-gray-100"
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="3.5"
                    />
                    <path
                      className="text-black"
                      strokeDasharray={`${usedPercentage}, 100`}
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="3.5"
                      strokeLinecap="round"
                    />
                  </svg>
                  <div className="absolute inset-0 flex items-center justify-center flex-col text-center">
                    <span className="text-sm font-black">{totalUsedMb} MB</span>
                    <span className="text-[9px] text-text-muted font-semibold">of 10 GB</span>
                  </div>
                </div>

                <div className="w-full space-y-2">
                  <div className="flex justify-between text-[11px] font-bold text-text-main">
                    <span>Used Space</span>
                    <span>{usedPercentage}%</span>
                  </div>
                  <div className="w-full h-1.5 bg-gray-100 rounded-full overflow-hidden">
                    <div className="h-full bg-black rounded-full transition-all" style={{ width: `${usedPercentage}%` }}></div>
                  </div>
                  <p className="text-[10px] text-text-muted font-medium">Synchronized with Google Cloud Firestore</p>
                </div>
              </div>
            </div>

            <button 
              onClick={() => {
                const confirmed = window.confirm("Clear demo documents and reset local document cache?");
                if (confirmed) {
                  localStorage.removeItem(LOCAL_STORAGE_KEY);
                  setDocuments(INITIAL_DEMO_DOCUMENTS);
                  setStatusNotice({ message: "Cache refreshed", type: "success" });
                }
              }}
              className="w-full flex items-center justify-center py-2.5 bg-white border border-border-main rounded-xl text-xs font-bold hover:bg-bg-subtle transition-colors shadow-2xs"
            >
              Reset Storage Cache
            </button>
          </div>

          {/* Quick Actions Card */}
          <div className="bg-white border border-border-main rounded-2xl p-6 shadow-sm flex flex-col justify-between">
            <div>
              <h3 className="font-bold text-sm text-text-main mb-4">Quick Actions</h3>
              
              <div className="grid grid-cols-2 gap-3">
                <div 
                  onClick={() => setIsUploadModalOpen(true)}
                  className="flex items-start gap-2.5 p-2.5 rounded-xl hover:bg-bg-subtle transition-colors cursor-pointer group border border-transparent hover:border-border-main"
                >
                  <div className="mt-0.5 w-7 h-7 rounded-lg border border-border-main flex items-center justify-center shrink-0 group-hover:bg-black group-hover:text-white transition-colors">
                    <Upload size={13} strokeWidth={2.5} />
                  </div>
                  <div>
                    <h4 className="font-bold text-xs text-text-main">Upload Document</h4>
                    <p className="text-[10px] text-text-muted mt-0.5">Firebase / Local</p>
                  </div>
                </div>
                
                <div 
                  onClick={() => router.push("/dashboard/describe-issue")}
                  className="flex items-start gap-2.5 p-2.5 rounded-xl hover:bg-bg-subtle transition-colors cursor-pointer group border border-transparent hover:border-border-main"
                >
                  <div className="mt-0.5 w-7 h-7 rounded-lg border border-border-main flex items-center justify-center shrink-0 group-hover:bg-black group-hover:text-white transition-colors">
                    <Sparkles size={13} strokeWidth={2.5} />
                  </div>
                  <div>
                    <h4 className="font-bold text-xs text-text-main">Generate Notice</h4>
                    <p className="text-[10px] text-text-muted mt-0.5">Draft with AI</p>
                  </div>
                </div>

                <div 
                  onClick={() => router.push("/dashboard/document-analysis")}
                  className="flex items-start gap-2.5 p-2.5 rounded-xl hover:bg-bg-subtle transition-colors cursor-pointer group border border-transparent hover:border-border-main"
                >
                  <div className="mt-0.5 w-7 h-7 rounded-lg border border-border-main flex items-center justify-center shrink-0 group-hover:bg-black group-hover:text-white transition-colors">
                    <Scan size={13} strokeWidth={2.5} />
                  </div>
                  <div>
                    <h4 className="font-bold text-xs text-text-main">Analyze Clauses</h4>
                    <p className="text-[10px] text-text-muted mt-0.5">Detect loopholes</p>
                  </div>
                </div>

                <div 
                  onClick={() => router.push("/dashboard/ai-assistant")}
                  className="flex items-start gap-2.5 p-2.5 rounded-xl hover:bg-bg-subtle transition-colors cursor-pointer group border border-transparent hover:border-border-main"
                >
                  <div className="mt-0.5 w-7 h-7 rounded-lg border border-border-main flex items-center justify-center shrink-0 group-hover:bg-black group-hover:text-white transition-colors">
                    <Scale size={13} strokeWidth={2.5} />
                  </div>
                  <div>
                    <h4 className="font-bold text-xs text-text-main">AI Assistant</h4>
                    <p className="text-[10px] text-text-muted mt-0.5">Ask questions</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Tips Card */}
          <div className="bg-[#F8FAFC] border border-[#E2E8F0] rounded-2xl p-6 shadow-sm relative overflow-hidden flex flex-col justify-between">
            <div className="relative z-10">
              <div className="flex items-center gap-2 mb-4">
                <Lightbulb size={20} className="text-text-main" />
                <h3 className="font-bold text-sm text-text-main">Legal Evidence Tips</h3>
              </div>
              <ul className="space-y-3 text-[11px] text-text-main font-semibold">
                <li className="flex items-start gap-2">
                  <Check size={14} className="mt-0.5 shrink-0 text-emerald-600" />
                  <span className="leading-relaxed">Keep original bank transaction IDs and unedited screenshots.</span>
                </li>
                <li className="flex items-start gap-2">
                  <Check size={14} className="mt-0.5 shrink-0 text-emerald-600" />
                  <span className="leading-relaxed">PDF leases & offer letters are analyzed with Gemini for unfair clauses.</span>
                </li>
                <li className="flex items-start gap-2">
                  <Check size={14} className="mt-0.5 shrink-0 text-emerald-600" />
                  <span className="leading-relaxed">Saved files are encrypted and accessible across your logged-in devices.</span>
                </li>
              </ul>
            </div>
            
            <div className="absolute -bottom-6 -right-6 text-gray-200/60 z-0">
              <Scale size={120} strokeWidth={1} />
            </div>
          </div>

        </div>

      </div>

      {/* Upload Document Modal */}
      {isUploadModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-200">
          <div className="bg-white border border-border-main rounded-3xl max-w-lg w-full p-6 shadow-2xl relative space-y-5">
            
            {/* Modal Header */}
            <div className="flex items-center justify-between pb-3 border-b border-border-main">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-black text-white flex items-center justify-center shadow-xs">
                  <CloudUpload size={16} />
                </div>
                <div>
                  <h3 className="font-black text-base text-text-main">Upload Legal Document</h3>
                  <p className="text-[11px] text-text-muted font-medium">Save to Firebase Cloud or LocalStorage</p>
                </div>
              </div>
              <button 
                onClick={() => setIsUploadModalOpen(false)}
                className="w-8 h-8 rounded-full bg-bg-subtle flex items-center justify-center text-text-muted hover:text-text-main"
              >
                <X size={16} />
              </button>
            </div>

            {/* Modal Form */}
            <form onSubmit={handleUploadSubmit} className="space-y-4">
              
              {/* Drop Zone */}
              <div 
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleDrop}
                onClick={() => fileInputRef.current?.click()}
                className="border-2 border-dashed border-border-main hover:border-black rounded-2xl p-6 text-center cursor-pointer transition-all bg-bg-subtle/50 hover:bg-bg-subtle"
              >
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileChange} 
                  accept=".pdf,.doc,.docx,.txt,image/*" 
                  className="hidden" 
                />
                
                {selectedFile ? (
                  <div className="flex items-center justify-center gap-3">
                    <FileCheck size={32} className="text-emerald-600" />
                    <div className="text-left">
                      <p className="font-black text-xs text-text-main truncate max-w-[240px]">{selectedFile.name}</p>
                      <p className="text-[10px] text-text-muted">{formatBytes(selectedFile.size)} • Click to change</p>
                    </div>
                  </div>
                ) : (
                  <div>
                    <Upload size={28} className="mx-auto text-text-muted mb-2" />
                    <p className="font-bold text-xs text-text-main">Click to select or drag and drop document</p>
                    <p className="text-[10px] text-text-muted mt-1">Supports PDF, DOCX, TXT, PNG, JPG (up to 25MB)</p>
                  </div>
                )}
              </div>

              {/* Document Title */}
              <div>
                <label className="block text-xs font-bold text-text-main mb-1">Document Title *</label>
                <input 
                  type="text" 
                  required
                  value={uploadDocName}
                  onChange={(e) => setUploadDocName(e.target.value)}
                  placeholder="e.g. Tenancy Agreement 2026 or Police Memo"
                  className="w-full px-3.5 py-2.5 bg-bg-subtle border border-border-main rounded-xl text-xs font-semibold outline-none focus:border-black focus:ring-1 focus:ring-black"
                />
              </div>

              {/* Document Category & Related Case Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-text-main mb-1">Category</label>
                  <select
                    value={uploadDocType}
                    onChange={(e: any) => setUploadDocType(e.target.value)}
                    className="w-full px-3 py-2 bg-bg-subtle border border-border-main rounded-xl text-xs font-bold text-text-main outline-none cursor-pointer"
                  >
                    <option value="Evidence">Evidence / Proof</option>
                    <option value="Agreement / Contract">Agreement / Contract</option>
                    <option value="Legal Notice">Legal Notice</option>
                    <option value="Financial Record">Financial Record</option>
                    <option value="ID Proof">Identity Document</option>
                    <option value="Other">Other Legal Paper</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-text-main mb-1">Related Case</label>
                  <input 
                    type="text"
                    value={uploadRelatedCase}
                    onChange={(e) => setUploadRelatedCase(e.target.value)}
                    placeholder="e.g. Deposit Refund Case"
                    className="w-full px-3 py-2 bg-bg-subtle border border-border-main rounded-xl text-xs font-semibold outline-none focus:border-black focus:ring-1 focus:ring-black"
                  />
                </div>
              </div>

              {/* Storage Destination Choice */}
              <div>
                <label className="block text-xs font-bold text-text-main mb-1.5">Storage Destination</label>
                <div className="grid grid-cols-3 gap-2">
                  <button
                    type="button"
                    onClick={() => setStorageDestination("both")}
                    className={`p-2.5 rounded-xl border text-center transition-all ${
                      storageDestination === "both"
                        ? "bg-black text-white border-black font-bold shadow-2xs"
                        : "bg-white text-text-muted border-border-main hover:bg-bg-subtle font-semibold"
                    }`}
                  >
                    <p className="text-[11px] leading-tight">Dual Sync</p>
                    <p className="text-[9px] opacity-75 mt-0.5">Cloud + Local</p>
                  </button>

                  <button
                    type="button"
                    onClick={() => setStorageDestination("firebase")}
                    className={`p-2.5 rounded-xl border text-center transition-all ${
                      storageDestination === "firebase"
                        ? "bg-black text-white border-black font-bold shadow-2xs"
                        : "bg-white text-text-muted border-border-main hover:bg-bg-subtle font-semibold"
                    }`}
                  >
                    <p className="text-[11px] leading-tight">Firebase</p>
                    <p className="text-[9px] opacity-75 mt-0.5">Cloud Only</p>
                  </button>

                  <button
                    type="button"
                    onClick={() => setStorageDestination("localstorage")}
                    className={`p-2.5 rounded-xl border text-center transition-all ${
                      storageDestination === "localstorage"
                        ? "bg-black text-white border-black font-bold shadow-2xs"
                        : "bg-white text-text-muted border-border-main hover:bg-bg-subtle font-semibold"
                    }`}
                  >
                    <p className="text-[11px] leading-tight">LocalStorage</p>
                    <p className="text-[9px] opacity-75 mt-0.5">Offline Device</p>
                  </button>
                </div>
              </div>

              {/* Actions */}
              <div className="flex items-center justify-end gap-2 pt-2 border-t border-border-main">
                <button
                  type="button"
                  onClick={() => setIsUploadModalOpen(false)}
                  className="px-4 py-2.5 border border-border-main rounded-xl text-xs font-bold text-text-main hover:bg-bg-subtle"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isUploading}
                  className="px-5 py-2.5 bg-black text-white rounded-xl text-xs font-bold hover:bg-neutral-800 transition-all flex items-center gap-2 disabled:opacity-50"
                >
                  {isUploading ? (
                    <>
                      <Loader2 size={14} className="animate-spin" /> Saving...
                    </>
                  ) : (
                    <>
                      <Check size={14} /> Save Document
                    </>
                  )}
                </button>
              </div>

            </form>
          </div>
        </div>
      )}

      {/* Document Details & Preview Modal */}
      {previewDoc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-200">
          <div className="bg-white border border-border-main rounded-3xl max-w-xl w-full p-6 shadow-2xl relative space-y-4">
            <div className="flex items-start justify-between pb-3 border-b border-border-main">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-bg-subtle border border-border-main flex items-center justify-center">
                  <FileText size={20} className="text-text-main" />
                </div>
                <div>
                  <h3 className="font-black text-base text-text-main truncate max-w-[340px]">{previewDoc.name}</h3>
                  <p className="text-xs text-text-muted">{previewDoc.relatedCase}</p>
                </div>
              </div>
              <button 
                onClick={() => setPreviewDoc(null)}
                className="w-8 h-8 rounded-full bg-bg-subtle flex items-center justify-center text-text-muted hover:text-text-main"
              >
                <X size={16} />
              </button>
            </div>

            {/* Document Details Grid */}
            <div className="grid grid-cols-2 gap-3 text-xs bg-bg-subtle/50 p-3.5 rounded-2xl border border-border-main">
              <div>
                <p className="text-[10px] text-text-muted font-bold uppercase">Category</p>
                <p className="font-extrabold text-text-main mt-0.5">{previewDoc.type}</p>
              </div>
              <div>
                <p className="text-[10px] text-text-muted font-bold uppercase">Storage Source</p>
                <p className="font-extrabold text-text-main mt-0.5">
                  {previewDoc.storageTarget === "firebase" ? "Firebase Firestore" : "Browser LocalStorage"}
                </p>
              </div>
              <div>
                <p className="text-[10px] text-text-muted font-bold uppercase">Uploaded On</p>
                <p className="font-extrabold text-text-main mt-0.5">{previewDoc.uploadedOn}</p>
              </div>
              <div>
                <p className="text-[10px] text-text-muted font-bold uppercase">File Size</p>
                <p className="font-extrabold text-text-main mt-0.5">{previewDoc.size}</p>
              </div>
            </div>

            {/* Preview Frame if DataUrl is available */}
            {previewDoc.dataUrl && previewDoc.dataUrl.startsWith("data:image") ? (
              <div className="border border-border-main rounded-2xl overflow-hidden max-h-60 flex items-center justify-center bg-gray-50">
                <img src={previewDoc.dataUrl} alt={previewDoc.name} className="max-h-60 object-contain" />
              </div>
            ) : (
              <div className="border border-dashed border-border-main rounded-2xl p-4 text-center bg-bg-subtle/40">
                <FileCheck size={28} className="mx-auto text-emerald-600 mb-1" />
                <p className="font-bold text-xs text-text-main">Verified Legal Record</p>
                <p className="text-[11px] text-text-muted">Document payload cached and verified under Indian Evidence Act guidelines.</p>
              </div>
            )}

            {/* Modal Actions */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-2 pt-3 border-t border-border-main">
              <button
                onClick={() => handleDeleteDocument(previewDoc.id)}
                className="w-full sm:w-auto px-4 py-2 text-xs font-bold text-red-600 hover:bg-red-50 rounded-xl transition-colors flex items-center justify-center gap-1.5"
              >
                <Trash2 size={14} /> Delete
              </button>

              <div className="flex items-center gap-2 w-full sm:w-auto">
                <button
                  onClick={() => handleDownload(previewDoc)}
                  className="flex-1 sm:flex-initial px-4 py-2 border border-border-main text-text-main hover:bg-bg-subtle rounded-xl text-xs font-bold flex items-center justify-center gap-1.5"
                >
                  <Download size={14} /> Download
                </button>
                <button
                  onClick={() => handleAnalyzeWithAI(previewDoc)}
                  className="flex-1 sm:flex-initial px-4 py-2 bg-black text-white hover:bg-neutral-800 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 shadow-xs"
                >
                  <Sparkles size={14} /> Analyze with AI
                </button>
              </div>
            </div>

          </div>
        </div>
      )}

    </main>
  );
}
